export const All = [
    {
        number: 210203,
        thumb: 'gif',
        type: ['Motion', 'Illustration'],
        en: 'The world where children live',
        ko: '아이들이 사는 세상',
        enTxt: '‘The World where Children Live’ is a special animation from ‘Knowledge Channel e’ series. The protagonist, who has spent childhood and adolescence through child abuse from parents, is trying to escape from the shadow of abuse as an adult. It was produced based on the note written by a child abuse victim.',
        enEtc: 'Scope: Animation</br>Client: EBS</br>Year: 2021',
        koTxt: '‘아이들이 사는 세상’은 EBS ‘지식채널 e’ 시리즈의 특별편 애니메이션입니다. 부모로부터 아동학대를 겪으며 보낸 유년기와 청소년기를 보낸 주인공이 성인이 되어 학대의 그림자에서 벗어나고자 노력하는 모습을 담고 있습니다. 실제 아동학대 수기를 바탕으로 제작되었습니다.',
        koEtc: '작업범위: 애니메이션 제작</br>의뢰: EBS</br>제작시기: 2021년',
        imgs: ['00_tw1.gif', '01_tw2.jpg', '02_tw2.jpg', '03_tw2.jpg', '04_tw2.jpg', '05_tw1.gif', '06_tw2.jpg', '07_tw2.jpg', '08_tw2.gif', '09_tw2.gif', '10_tw1.gif', '11_tw2.jpg', '12_tw2.jpg', '13_tw1.jpg',],
        video: { position: 'none', },
    },
    {
        number: 210202,
        thumb: 'gif',
        type: ['Motion', 'Illustration'],
        en: 'Why are we ashamed?',
        ko: '우리는 왜 부끄러움을 느낄까?',
        enTxt: '‘Why Are We Ashamed?’ is a special animation from ‘Knowledge Channel e’ series. This animation introduces shame, the universal emotion of mankind, through various studies and related Greek mythology. While shame can only feel uncomfortable and embarrassing, it is emphasized that it is essential to sustaining a community and society.',
        enEtc: 'Scope: Animation</br>Client: EBS</br>Year: 2021',
        koTxt: '‘우리는 왜 부끄러움을 느낄까?’는 EBS ‘지식채널 e’ 시리즈의 특별편 애니메이션입니다. 다양한 연구와 관련된 그리스 신화를 통해 인류의 보편적 감정인 부끄러움을 소개합니다. 부끄러움은 불편하고 난감하게만 느껴지지만, 알고 보면 공동체와 사회를 유지하는 데 꼭 필요한 요소임을 역설합니다.',
        koEtc: '작업범위: 애니메이션 제작</br>의뢰: EBS</br>제작시기: 2021년',
        imgs: ['01_tw1.gif', '02_tw2.jpg', '03_tw2.jpg', '04_tw1.gif', '05_tw2.gif', '06_tw2.gif', '07_tw2.jpg', '08_tw2.jpg', '09_tw1.gif', '10_tw2.jpg', '11_tw2.jpg',],
        video: { position: 'none', },
    },
    {
        number: 210201,
        thumb: 'gif',
        type: ['Motion', 'Illustration'],
        en: 'Waiting for him to come',
        ko: '그분이 오시기를',
        enTxt: '‘Waiting for him to come’ is a special animation from ‘Knowledge Channel e’ series. Many artists await inspiration in the creative process. Until the inspiration they await arrives, artists constantly repeat their routines and take unique actions. This animation is a fun introduction to the creative process of artists through various examples of actual figures such as John Steinbeck, Glenn Gould and Tchaikovsky.',
        enEtc: 'Scope: Animation</br>Client: EBS</br>Year: 2021',
        koTxt: '‘그분이 오시기를’은 EBS ‘지식채널 e’ 시리즈의 특별편 애니메이션입니다. 많은 예술가들이 창작의 과정에서 영감을 기다립니다. ‘그 분’, 즉 영감이 찾아오기까지 예술가들은 끊임없이 루틴을 반복하기도 하고, 기행을 일삼기도 합니다. 존 스타인벡, 글렌 굴드, 차이코프스키 등 실제 인물들의 다양한 사례를 통해 예술가들의 창작과정을 재미있게 소개합니다.',
        koEtc: '작업범위: 애니메이션 제작</br>의뢰: EBS</br>제작시기: 2021년',
        imgs: ['01_tw1.gif', '02_tw2.jpg', '03_tw2.jpg', '04_tw2.gif', '05_tw2.gif', '56_tw1.jpg', '07_tw2.jpg', '08_tw2.jpg', '09_tw1.gif', '10_tw2.jpg', '11_tw2.jpg',],
        video: { position: 'none', },
    },
    {
        number: 210101,
        thumb: 'jpg',
        type: ['Editorial', 'Illustration', 'Graphics'],
        en: 'Fisher’s Kitchen',
        ko: '어부의 밥상에는 게미가 있다',
        enTxt: 'This book is a collection of stories about the sea and the home meals of people who have lived with the sea in Namhae. Through the interview format, memories of Namhae’s seasonal ingredients, recipes, and food are warmly introduced in dialect. The various ingredients introduced in the text are inserted as illustrations to help readers understand.',
        enEtc: 'Scope: Book design, illustration</br>Size: 140mm ✕ 200mm (212p)</br>Text and interview: Seungyong Choi, Dajung Han</br>Client: 3people</br>Year: 2021',
        koTxt: '남해에서 바다와 함께 살아온 사람들의 집밥과 바다에 얽힌 이야기를 모은 책입니다. 인터뷰 형식을 통해 남해의 제철 식재료, 요리법과 음식에 얽힌 추억들이 사투리로 정겹게 소개됩니다. 본문에서 소개되는 다양한 식재료는 일러스트레이션으로 삽입되어 독자의 이해를 돕습니다.',
        koEtc: '작업범위: 표지 및 본문 디자인, 일러스트레이션</br>판형: 140mm ✕ 200mm (212p)</br>글과 인터뷰: 최승용, 한다정</br>의뢰: 쓰리피플</br>제작시기: 2021년',
        imgs: ['01_tw1.jpg', '02_tw1.jpg', '03_tw1.jpg', '04_tw1.jpg', '05_tw1.jpg', '06_tw1.jpg', '07_tw1.jpg', '08_tw1.jpg', '09_tw1.jpg', '10_tw1.jpg',],
        video: { position: 'none', },
    },
    {
        number: 201201,
        thumb: 'gif',
        type: ['Motion', 'Illustration'],
        en: 'Adventskalendar',
        ko: '산타를 위한 아드벤츠칼렌더',
        enTxt: '‘Adventskalendar’ is a German Christmas tradition, a special calendar in December that allows people to open presents one by one while waiting for Christmas. For Santa Claus who needs to increase his fitness ahead of the Christmas gift delivery, we have given an Adventskalendar with different exercises every day. Through the Instagram @Would_it_be_okay account, a video of Santa exercising from December 1st to 24th was serialized one at a time a day, and re-produced as a video including an intro and an outro that contains the story of Santa Claus.',
        enEtc: 'Scope: Animation planning and production</br>Self-initiated</br>Year: 2020',
        koTxt: '‘아드벤츠칼렌더’는 독일 크리스마스 전통으로, 12월에 사람들이 크리스마스를 기다리며 하나씩 선물을 열어볼 수 있게 만들어진 특별한 달력입니다. 크리스마스 선물 배달을 앞두고 체력을 키워야 하는 산타클로스를 위해, 매일 다른 운동이 들어 있는 아드벤츠칼렌더를 선물했습니다. 인스타그램 @Would_it_be_okay 계정을 통해 12월 1일부터 24일까지 운동하는 산타 영상이 하루에 한 개씩 연재되었고, 산타클로스의 이야기를 담은 인트로와 아웃트로를 포함한 영상으로 다시 제작되었습니다.',
        koEtc: '작업범위: 애니메이션 기획 및 제작</br>자체 프로젝트</br>제작시기: 2020년',
        imgs: ['01_tw2.gif', '02_tw2.gif', '03_tw2.gif', '04_tw2.gif', '05_tw2.gif', '06_tw2.gif', '07_tw1.gif', '08_tw1.gif', '09_tw1.gif',],
        video: { position: 'none', },
    },
    {
        number: 201001,
        thumb: 'gif',
        type: ['Motion', 'Illustration'],
        en: 'Banana House',
        ko: '바나나 하우스',
        enTxt: 'The video introduces the ‘Banana House’, a service that allows you to learn programming in an easy and fun way. Users learn the basic principles of programming while growing bananas through an app linked to a smart farm located in Jeju Island. Through the image of a child using the service, we tried to include the contents of ‘Banana House’ in a short video in an easy and friendly way.',
        enEtc: 'Scope: Animation planning and production</br>Client: Sams Games</br>Year: 2020',
        koTxt: '쉽고 재미있게 프로그래밍을 배울 수 있는 서비스 ‘바나나 하우스’를 소개하는 영상입니다. 사용자는 제주도에 위치한 스마트팜과 연동된 앱을 통해 바나나를 키우면서 프로그래밍의 기본 원리를 배우게 됩니다. 서비스를 사용하는 아이의 모습을 통해 짧은 영상 안에 ‘바나나 하우스’의 내용을 쉽고 친근하게 담고자 하였습니다.',
        koEtc: '작업범위: 애니메이션 기획 및 제작</br>의뢰 : 샘스게임즈</br>제작시기: 2020년',
        imgs: ['00_tw2.png', '01_tw2.png', '02_tw2.png', '03_tw2.png', '04_tw1.gif', '05_tw2.png', '06_tw2.png', '07_tw1.gif', '08_tw2.png', '09_tw2.png',],
        video: { position: 'none', },
    },
    {
        number: 200901,
        thumb: 'jpg',
        type: ['Branding', 'Graphics'],
        en: 'Visual identity for Nodo island',
        ko: '소설의 숲, 노도',
        enTxt: 'Nodo is a small island about 2km away from Byulryeon Port in Namhae, Gyeongsangnam-do, where Seopo Kim Man-jung, the author of 〈Guunmong〉 and 〈Sassinamjeonggi〉, was exiled. The logo and visual identity for Nodo was created by linking the vitality of the story felt in the slogan “Nodo, the Forest of Novel” with the shape of an island which is reminiscent of an acorn. In addition, we designed a sign system, brochure for visitors and a poster that recruits artists to reside in the Nodo creation room',
        enEtc: 'Scope: Logo, visual identity, signage, leaflet, poster</br>Client: Namhae county office / Heterotipia</br>Photo: Huisoo Yang (Maparam photo studio)</br>Year: 2020',
        koTxt: '노도는 경상남도 남해 벽련항에서 2km정도 떨어진 작은 섬으로, 〈구운몽〉, 〈사씨남정기〉의 작가 서포 김만중이 유배되었던 곳입니다. ‘소설의 숲, 노도’라는 슬로건에서 느껴지는 이야기의 생명력을 상수리 열매 모양의 섬의 형태와 연결지어 로고를 만들고, 노도를 표현하는 비주얼 아이덴티티를 제시했습니다. 추가적으로 방문객을 위한 사이니지와 안내책자, 노도 창작실 입주작가 공모 포스터 등을 디자인했습니다.',
        koEtc: '작업범위: 로고와 비주얼 아이덴티티, 사이니지, 리플렛, 포스터</br>의뢰: 남해군청 / 헤테로토피아</br>사진: 마파람사진관 양희수</br>제작시기: 2020년',
        imgs: ['01_tw1.jpg', '02_tw1.jpg', '03_tw1.jpg', '04_tw1.jpg', '05_tw1.jpg', '06_tw1.jpg', '07_tw1.jpg', '08_mw1.jpg', '09_mw1.jpg', '10_tw2.jpg', '11_tw2.jpg', '12_tw2.jpg', '13_tw2.jpg', '14_tw2.jpg', '15_tw2.jpg',],
        video: { position: 'none', },
    },
    {
        number: 191201,
        thumb: 'jpg',
        type: ['Editorial', 'Illustration'],
        en: 'Protected trees of Namhae',
        ko: '남해 보호수',
        enTxt: '‘Protected trees of Namhae’ is the first book of the Namhae Conservation Map Project. About 30 old trees in Namhae-gun are introduced with illustrations, one tree per page. It contains basic information such as tree species, characteristics, location, and size of each tree, along with stories about trees and villages. On the last page, there is a conservation map showing all the trees so one can easily locate them. The illustrations contained in the book were displayed at the exhibition ‘Guardian of the Village, Namhae Protected Trees’ (at Simun-dolchanggo, April 25-October 4, 2020).',
        enEtc: 'Scope: Book design, illustration</br>Size: 150mm ✕ 250mm (40p)</br>Author: Hanki Jo, Seungyong Choi</br>Client: 3people</br>Year: 2020',
        koTxt: '남해 보존지도프로젝트의 첫 번째 책인 ‘남해 보호수’를 그리고 디자인했습니다. 남해군에 있는 30여그루의 노거수를 한 페이지에 한 나무씩 일러스트레이션과 함께 소개합니다. 각 나무의 수종, 특징, 위치, 크기 등 기본 정보와 함께 나무와 마을에 얽힌 이야기를 실었습니다. 마지막 장에는 모든 나무가 표시된 보존지도가 있어 쉽게 위치를 찾아볼 수 있습니다. 책에 수록된 일러스트는 ‘마을의 수호자, 남해 보호수 展’ (시문돌창고, 2020. 4. 25 - 10. 4) 에서 전시되었습니다.',
        koEtc: '작업범위: 표지 및 본문 디자인, 일러스트레이션</br>판형: 150mm ✕ 250mm (40p)</br>저자: 조한기, 최승용</br>의뢰: 쓰리피플</br>제작시기: 2020년',
        imgs: ['03_mw1.jpg', '04_mw1.jpg', '05_mw1.jpg', '06_mw1.jpg', '07_mw1.jpg',],
        video: { position: 'none', },
    },
    {
        number: 190902,
        thumb: 'jpg',
        type: ['Graphics'],
        en: 'Start from the end',
        ko: '끝을시작',
        enTxt: 'Poster and leaflet design for the exhibition ‘Start from the end’. Namhaegak, a building built in 1975 as a rest area to view Namhae Bridge, became an abandoned space that people did not visit as time passed. In the process of regenerating Namhaegak into a new cultural space, this exhibition shows the traces of the past remaining in this place and the process of change. The poster was designed in a way that collaged parts of the old and unmanaged buildings in Namhaegak and rearranged them in a virtual space.',
        enEtc: 'Scope: Poster, leaflet, banner</br>Client: Heterotipia</br>Year: 2019',
        koTxt: '‘끝을시작: 부정을 부정하지 않는다’ 전시의 포스터와 리플렛 등 전시 홍보 디자인물을 제작했습니다. 1975년 남해대교를 전망하기 위한 휴게소 용도로 지어진 건물인 남해각은 시간이 흘러 사람들이 찾지 않는 버려진 공간이 되었습니다. 이 전시는 남해각을 새로운 문화공간으로 재생하는 과정에서 이 장소에 남아있는 과거의 흔적과 변화의 과정을 보여줍니다. 낡고 관리되지 않은 남해각 건물의 부분들을 콜라주해 가상의 공간에 재배치하는 방식으로 포스터를 디자인했습니다.',
        koEtc: '작업범위: 포스터, 리플렛, 배너</br>의뢰: 헤테로토피아</br>제작시기: 2019년',
        imgs: ['01_mw1.jpg', '02_mw1.jpg', '03_mw1.jpg',],
        video: { position: 'none', },
    },
    {
        number: 190901,
        thumb: 'jpg',
        type: ['Branding', 'Graphics'],
        en: 'Namhaegak Archive',
        ko: '남해각 아카이브',
        enTxt: 'Logo, illustration and website visual concept for the ‘Namhaegak Archive’ project. Namhaegak, a building built in 1975 as a rest area to view Namhae Bridge, became an abandoned space that people did not visit as time passed. The ‘Namhaegak Archive’ is a project to record and store the stories and photos related to Namhae Bridge and the old Namhaegak, in the process of regenerating Namhaegak as a new cultural space.',
        enEtc: 'Scope: Logo, illustration, website visual concept</br>Client: Heterotipia</br>Website creation: Yuta Sugihara</br>Photo: Kyung Roh</br>Year: 2019',
        koTxt: '‘남해각 아카이브’ 프로젝트를 위한 로고와 일러스트레이션, 웹사이트 비주얼 컨셉을 제작했습니다. 1975년 남해대교를 전망하기 위한 휴게소 용도로 지어진 건물인 남해각은 시간이 흘러 사람들이 찾지 않는 버려진 공간이 되었습니다. ‘남해각 아카이브’는 남해각을 새로운 문화공간으로 재생하는 과정에서 남해대교와 옛 남해각에 얽힌 사람들의 이야기와 사진을 기록하고 보관하는 프로젝트입니다. ',
        koEtc: '작업범위: 로고, 일러스트레이션, 웹사이트 비주얼 컨셉</br>의뢰: 헤테로토피아</br>웹사이트 제작: 스기하라 유타</br>사진: 노경</br>제작시기: 2019년',
        imgs: ['01_tw2.jpg', '02_tw2.jpg', '03_tw1.jpg', '04_tw1.jpg', '05_tw1.jpg',],
        video: { position: 'none', },
    },
    {
        number: 190702,
        thumb: 'jpg',
        type: ['Graphics'],
        en: 'Leaves',
        ko: '이파리',
        enTxt: 'A Poster and leaflet for the exhibition 〈Leaves〉 by Inhye Jung. She draws the vitality of various plants, including cactus, through her subjective colors and clunky brushstrokes. In reference to the client’s request to express the feeling of the exhibition without directly revealing the works, we placed a low-saturation, colorful leaf-shaped graphic motifs to create an image for the exhibition.',
        enEtc: 'Scope: Poster, leaflet</br>Artist: Inhye Jung</br>Client: Dolchanggo project</br>Year: 2019',
        koTxt: '정인혜 작가의 〈이파리〉 전시를 위한 포스터와 리플렛을 디자인했습니다. 정인혜 작가는 자연의 색보다 한 톤 다운된 주관적 색채와 투박한 붓터치를 통해 선인장을 비롯한 다양한 식물들의 생명력을 그려냅니다. 작품을 직접적으로 드러내지 않고 전시의 느낌을 표현해 달라는 요청을 참고하여, 채도가 낮고 알록달록한 잎 모양 그래픽 모티프를 사용해 전시를 위한 이미지를 제작했습니다.',
        koEtc: '작업범위: 포스터, 리플렛</br>작가: 정인혜</br>의뢰: 돌창고프로젝트</br>제작시기: 2019년',
        imgs: ['01_mw1.jpg', '02_mw1.jpg', '03_mw1.jpg',],
        video: { position: 'none', },
    },
    {
        number: 190601,
        thumb: 'jpg',
        type: ['Branding', 'Graphics'],
        en: 'Business card for Heterotopia',
        ko: '헤테로토피아 명함',
        enTxt: 'Business card designs for members of ‘Heterotopia’, who are doing cultural planning on the theme of local culture and spaces. The basic format of the first business card is unified, but the color can be chosen by members to express their individuality. The second business card is designed so that the name stroke on the front of the business card and the shape of the back of the business card are connected to express the act of ‘connecting people’.',
        enEtc: 'Scope: Business card</br>Client: Heterotipia</br>Year: 2019',
        koTxt: '지역문화와 공간을 중심으로 문화기획을 하는 ‘헤테로토피아’ 구성원들을 위한 두 가지 명함입니다. 첫 번째 명함은 기본 포맷은 통일되어 있지만 색상은 구성원들이 직접 골라 각자의 개성을 표현할 수 있습니다. 두 번째 명함은 ‘사람 사이를 잇는’ 행위를 표현하기 위해 명함 앞면의 이름 획과 명함 뒷면의 형태가 이어지도록 디자인했습니다.',
        koEtc: '작업범위: 명함</br>의뢰: 헤테로토피아</br>제작시기: 2019년',
        imgs: ['01_mw1.jpg', '02_mw1.jpg',],
        video: { position: 'none', },
    },
    {
        number: 190302,
        thumb: 'jpg',
        type: ['Editorial', 'Graphics'],
        en: 'Regeneration Travel',
        ko: '재생여행',
        enTxt: 'Book design for ‘Regeneration Travel’. After the author purchased Dolchanggo (a old stone warehouse built with natural stone) in Namhae for his ecological life and regional regeneration, he went on a trip to Japan contemplating what to do in Dolchanggo. The book contains travel stories of three cities: Naoshima, which regenerates the island through culture and art, Okayama, which uses old abandoned spaces as cultural spaces, and Tottori, where people living in large cities have migrated and brought life to the rural city.',
        enEtc: 'Scope: Book design</br>Size: 105mm ✕ 170mm (120p)</br>Author: Sungyong Choi</br>Client: 3people</br>Year: 2019',
        koTxt: '지역재생 여행기 ‘재생여행’ 책표지와 본문을 디자인했습니다. 필자는 자신의 생태적 삶과 지역재생에 대한 계획을 가지고 남해의 돌창고를 구입한 뒤, 돌창고에서 어떤 행위를 할지 고민하며 일본 여행을 떠납니다. 문화와 예술을 통해 섬을 재생시킨 나오시마, 오래되어 버려진 공간을 문화공간으로 활용한 오카야마, 대도시에 살던 사람들이 이주해 와 활기를 불어넣고 있는 돗토리 총 세 도시의 여행기가 책에 담겨있습니다. ',
        koEtc: '작업범위: 북디자인</br>판형: 105mm ✕ 170mm (120p)</br>저자: 최승용</br>의뢰: 쓰리피플</br>제작시기: 2019년',
        imgs: ['01_tw1.jpg', '02_tw1.jpg', '03_tw1.jpg', '04_tw1.jpg', '05_tw1.jpg',],
        video: { position: 'none', },
    },
    {
        number: 190301,
        thumb: 'jpg',
        type: ['Illustration', 'Graphics'],
        en: 'Book and package design for Kulkids',
        ko: '쿨키즈 컬러링북과 반창고 패키지',
        enTxt: 'We designed a coloring book and band-aid package for KulKids, a German children’s goods company that makes books and toys that respect the value of diversity. In the coloring book, people of various races, religions, and gender identities appear to express KulKids’ motto, “Für jedes Kind ein Spiegelbild”, so that all children can find themselves or their families in this book. In the band-aid package for various skin colors, the product features were expressed by putting illustrations of three children with different skin colors.',
        enEtc: 'Scope: Illustration, Book design, Package</br>Size: 210mm ✕ 210mm (28p)</br>Client: KulKids</br>Year: 2019, 2020',
        koTxt: '다양성의 가치를 존중하는 책과 완구를 만드는 독일 아동용품 회사, ‘쿨키즈’의 컬러링북과 반창고 패키지를 디자인했습니다. 컬러링북에는 쿨키즈의 모토인 ‘Für jedes Kind ein Spiegelbild’를 표현하기 위해, 즉 모든 어린이들이 자신 또는 자신 가족의 모습을 찾아볼 수 있도록 다양한 인종, 종교, 성정체성을 가진 사람들이 등장합니다. 다양한 피부색을 위한 반창고 패키지에는 피부색이 다른 세 명의 아이들 일러스트레이션을 넣어 제품의 특징을 표현했습니다.',
        koEtc: '작업범위: 일러스트레이션, 북디자인, 패키지</br>판형: 210mm ✕ 210mm (28p)</br>의뢰: 쿨키즈</br>제작시기: 2019년, 2020년',
        imgs: ['01_tw1.jpg', '02_tw1.jpg', '03_tw1.jpg', '04_tw1.jpg', '05_tw1.jpg', '06_tw1.jpg', '07_tw1.jpg',],
        video: { position: 'none', },
    },
    {
        number: 181001,
        thumb: 'jpg',
        type: ['Editorial'],
        en: 'We came to Namhae to paint',
        ko: '남해에 그림 그리러 왔어요',
        enTxt: '‘We came to Namhae to paint’ is a series of books in which artists who lived in Namhae through participation in the Dolchanggo Artist Residence Program in 2018 recorded their creative process and life from June to September. The artists spend the hot summer in Namhae, writing down the interactions between the region and the creative process, and their conflicts and concerns about work honestly in a diary. The calendar on the cover of the books is marked with circles of different sizes depending on the number of records written on that day.',
        enEtc: 'Scope: Book design</br>Size: 200mm ✕ 150mm (260p, 298p)</br>Authour: Seojin Kim, Jeonghyun Kim, Hyejin Yun, Jungin Won, Sumin Lee</br>Client: 3people</br>Year: 2018',
        koTxt: '‘남해에 그림 그리러 왔어요’는 2018년 돌창고 아티스트 레지던스 프로그램을 통해 남해에 입주한 작가들이 6월부터 9월에 걸쳐 창작과정과 생활을 기록한 책입니다. 작가들은 남해의 무더운 여름을 보내며 남해라는 지역과 창작과정의 상호작용, 서로간의 갈등과 고민을 일기로 솔직하게 풀어냅니다. 책 표지에 있는 달력에는 해당 날짜에 쓰인 기록의 개수에 따라 크기가 다른 원이 표시되어 있습니다.',
        koEtc: '작업범위: 북디자인</br>판형: 200mm ✕ 150mm (260p, 298p)</br>저자: 김서진, 김정현, 윤혜진, 원정인, 이수민</br>의뢰: 쓰리피플</br>제작시기: 2018년',
        imgs: ['01_mw1.jpg', '02_mw1.jpg', '03_mw1.jpg', '04_mw1.jpg', '05_mw1.jpg', '06_mw1.jpg', '07_mw1.jpg',],
        video: { position: 'none', },
    },
    {
        number: 180801,
        thumb: 'gif',
        type: ['Motion', 'Illustration'],
        en: 'Time in Namhae',
        ko: '남해의 시간',
        enTxt: '‘Time in Namhae’ is an animation depicting Namhae’s past and present through the life of an old man who has been living in Namhae. As a boy grows older and becomes a young man to a middle-aged and old man, Namhae undergoes also many changes. In the 90’s the bustling village became quiet due to the urbanization. And recently, the 2nd Namhae Bridge and new spaces have been createdand are rejuvenating Namhae. This animation was screened at the Dolchanggo through the group exhibition 〈Welcome to the South Sea, the Story of the People of the Namhae〉 (July 5, 2018-October 21, 2018). Subsequently, the production process, storyboard, and individual scenes were published through the exhibition and the book of the same name.',
        enEtc: 'Scope: Animation planning and production</br>Length: 4\' 38"</br>Background music: Sanghyun No</br>Assist: Haeun Kim</br>Client: Dolchanggo project</br>Year: 2018',
        koTxt: '‘남해의 시간’은 남해에서 한평생을 살아온 염소 치는 노인의 일생을 통해 남해의 과거와 현재를 그려낸 애니메이션입니다. 소년이 나이를 먹어 청년에서 중년, 장년이 되는 동안 남해도 많은 변화를 겪습니다. 북적거리던 마을이 90년대에 들어 이촌향도 현상으로 적막해지는가 하면, 최근 제2남해대교와 새로운 공간들이 생겨나면서 다시 활기를 찾기도 합니다. 〈어서오시다 - 남쪽 바다, 남해 사람들의 이야기〉 그룹전시를 통해 남해 돌창고에서 상영되었고, (2018년 7월 5일 - 10월 21일) 추후 제작과정과 스토리보드, 스틸컷 등이 전시와 동명의 책을 통해 출간되었습니다.',
        koEtc: '작업범위: 애니메이션 기획 및 제작</br>길이: 4\' 38"</br>배경음악: 노상현</br>도움: 김하은</br>의뢰: 돌창고프로젝트</br>제작시기: 2018년',
        imgs: ['00_tw2.jpg', '01_tw2.jpg', '02_tw2.jpg', '03_tw2.jpg', '04_tw1.gif', '05_tw1.gif', '06_tw2.jpg', '07_tw2.jpg', '08_tw2.jpg', '09_tw2.jpg', '10_tw1.gif',],
        video: { position: 'none', },
    },
    {
        number: 180701,
        thumb: 'jpg',
        type: ['Graphics',],
        en: 'Small Cloud Points',
        ko: '잔구름 지점',
        enTxt: 'The group exhibition ‘Small Cloud Points’ is an exhibition with the theme of omitted points in everyday life that are piled up like small clouds. Posters and promotional materials are designed with the keywords ‘omit’ and ‘overlap’. The photos of the sky and clouds used in the collage were cut from photos taken by five artists during their residency stay in Namhae.',
        enEtc: 'Scope: Poster, leaflet, artwork guide map, banner</br>Client: Heterotipia</br>Year: 2018',
        koTxt: '그룹전 ‘잔구름 지점’은 잔구름처럼 겹겹이 쌓인 일상의 생략된 지점들을 주제로 한 전시입니다. ‘생략’과 ‘중첩’이라는 키워드를 중심으로 포스터와 홍보물을 디자인했습니다. 콜라주에 사용한 하늘과 구름 사진은 다섯 명의 작가들이 남해에서 레지던시 체류기간동안 직접 촬영한 사진에서 오려 사용했습니다.',
        koEtc: '작업범위: 포스터, 리플렛, 작품안내도, 배너</br>의뢰: 헤테로토피아</br>제작시기: 2019년',
        imgs: ['01_tw1.jpg', '02_tw1.jpg', '03_tw1.jpg', '04_tw1.jpg',],
        video: { position: 'none', },
    },
    {
        number: 180101,
        thumb: 'jpg',
        type: [],
        en: 'Books for publisher YUL',
        ko: '도서출판율 단행본 디자인',
        enTxt: 'Design for three books about the artists, their friends and sponsors, translated by publisher YUL. ‘Gertrude Stein’s Autobiography of Alice B. Toklas’ is an autobiography of an American writer, poet and art collector Gertrude Stein’s lifelong companion, Alice B. Toklas. The story of many artists, writers, and socialites with whom Stein was interacting at the time is interestingly introduced. “My Gallery, My Painters” shows the birth and vivid development of Cubism through conversations between Daniel-Henri Kahnweiler, a living witness of the 20th century French painting bed, and Francis Cremieux, a journalist. “The Truth About Jacqueline and Pablo Picasso” describes the encounter and life between Pablo Picasso and Jacqueline Picasso, which were not well known.',
        enEtc: '',
        koTxt: '도서출판율에서 번역한 예술가들과 그들의 친구들, 후원자들에 대한 세 권의 책을 디자인했습니다. ‘거트루드 스타인이 쓴 앨리스 B. 토클라스 자서전’은 작가이지 시인, 극작가, 예술품 수집가인 거트루드 스타인이 쓴 그녀의 일생의 동반자 앨리스 B. 토클라스의 자서전입니다. 당시 스타인이 교류하던 많은 예술가, 작가, 사교계의 인물과의 일화가 흥미롭게 소개됩니다. ‘나의 화랑 나의 화가들’은 20세기 프랑스 화단의 살아있는 증인, 화상 다니엘 앙리-칸바일러와 기자인 프랑시스 크레미유의 대담을 통해 입체주의의 태동과 생생한 전개과정을 보여줍니다. ‘자클린과 파블로 피카소에 관한 진실’은 잘 알려지지 않았던 파블로 피카소와 자클린 피카소의 만남과 삶을 담고 있습니다.',
        koEtc: '작업범위: 북디자인</br>판형: 200mm ✕ 150mm (260p), </br>의뢰: 쓰리피플</br>제작시기: 2018년',
        imgs: [],
        video: { position: 'none', },
    },
    {
        number: 170402,
        thumb: 'jpg',
        type: ['Branding', 'Graphics'],
        en: 'Icon set for Naturing',
        ko: '네이처링 아이콘',
        enTxt: 'Species and habitat icon design for Naturing, an online-based natural activity sharing platform. When uploading a photo of found animals or plants, users can choose an icon that represents its species habitat and record the information together. To make it easy to distinguish, the species icons were created in a solid form and the habitat in a line form.',
        enEtc: 'Scope: Icon set, T-shirt design</br>T-shirt photo: Naturing</br>Client: Naturing</br>Year: 2017(Icon), 2021(T-shirt)',
        koTxt: '온라인 기반 자연활동 공유 플랫폼, 네이처링의 분류군, 서식지 아이콘을 디자인했습니다. 사용자가 발견한 생물을 촬영해 업로드할 때 해당 분류군과 서식지에 맞는 아이콘을 골라 함께 기록할 수 있습니다. 구분을 위해 분류군은 솔리드 형태, 서식지는 라인 형태로 제작했습니다. ',
        koEtc: '작업범위: 아이콘 세트, 티셔츠</br>티셔츠 사진제공: 네이처링</br>의뢰: 네이처링</br>제작시기: 2017년(아이콘), 2021년(티셔츠)',
        imgs: ['01_mw2.jpg', '02_mw2.jpg', '03_mw2.jpg', '04_mw2.jpg', '05_mw2.jpg', '06_mw2.jpg', '07_mw1.jpg', '08_mw1.jpg',],
        video: { position: 'none', },
    },
    {
        number: 170301,
        thumb: 'gif',
        type: ['Motion', 'Illustration'],
        en: 'Changes that brightly lit up Banishanta',
        ko: '반짝반짝 바니샨타를 밝힌 변화',
        enTxt: 'We made an animation to promote the Solar Station business of the Environmental Foundation. As part of the Asia support project, the Environmental Foundation distributed solar lantern for energy independence to villages with insufficient power infrastructure, and installed power generation stations for villages in Bangladesh and Cambodia. The animation ‘Changes That Shine Banishanta’ introduces the Solar Station business in an easy-to-understand manner and calls for attention.',
        enEtc: '',
        koTxt: '환경재단의 솔라스테이션 사업 홍보 애니메이션을 만들었습니다. 환경재단은 아시아 지원 사업의 일환으로 전력 인프라가 부족한 마을들의 에너지 자립을 위하여 태양광 전등을 나눠 주고, 방글라데시와 캄보디아에는 마을 공용의 발전 스테이션을 설치했습니다. 애니메이션 ‘반짝반짝 바니샨타를 밝힌 변화’는 이 솔라스테이션 사업을 알기 쉽게 소개하고 관심을 촉구합니다. ',
        koEtc: '',
        imgs: [],
        video: { position: 'none', },
    },
    {
        number: 170101,
        thumb: 'jpg',
        type: ['Illustration', 'Graphics'],
        en: 'Poster for Stone Market',
        ko: '돌장 포스터',
        enTxt: 'Poster design for the flea market ‘Doljang (stone market)’. Stones with simple market information such as location and contact information written on the back can be torn off and taken away.',
        enEtc: 'Scope: Poster</br>Client: Dolchanggo project</br>Year: 2017',
        koTxt: '플리마켓 ‘돌장’을 위한 포스터를 만들었습니다. 포스터에 있는 돌 모양은 뜯어내어 가져갈 수 있게 되어 있으며, 돌 모양 뒤쪽에는 돌장이 열리는 날짜와 장소, 문의처 등 간단한 정보가 적혀 있습니다.',
        koEtc: '작업범위: 포스터</br>의뢰: 돌창고프로젝트</br>제작시기: 2017년',
        imgs: ['01_tw1.jpg', '02_tw1.jpg', '03_tw1.jpg',],
        video: { position: 'none', },
    },
    {
        number: 161201,
        thumb: 'jpg',
        type: ['Graphics'],
        en: 'New year’s card for 2017',
        ko: '2017년 연하장',
        enTxt: 'New Year’s card design for 2017. A maze is drawn on one side of it and after passing through the maze, the words ‘Hello 2017 Goodbye 2016’ appear.',
        enEtc: 'Scope: New Year’s card</br>Self-initiated</br>Year: 2016',
        koTxt: '2017년을 맞아 만든 연하장입니다. 한쪽 면에 미로가 그려져 있으며, 미로를 통과하고 나면 ‘Hello 2017 Goodbye 2016’이라는 글자가 드러납니다.',
        koEtc: '작업범위: 연하장</br>자체 프로젝트</br>제작시기: 2016년',
        imgs: ['01_mw1.jpg', '02_mw1.jpg',],
        video: { position: 'none', },
    },
    {
        number: 161102,
        thumb: 'jpg',
        type: ['Branding', 'Graphics', 'Illustration'],
        en: 'ROOM&RUMOUR',
        ko: '룸앤루머',
        enTxt: 'Logo design for the band ROOM&RUMOUR and illustration for the cover of the single album 〈Suspended Animation〉. The logo created by dividing the initial ‘R’ of the band name into four can be also used as a frame on the album cover.',
        enEtc: 'Scope: Logo, album cover illustration</br>Client: ROOM&RUMOUR</br>Year: 2016',
        koTxt: '밴드 ROOM&RUMOUR의 로고를 디자인하고, 싱글 앨범 〈Suspended Animation〉의 커버에 들어가는 일러스트레이션을 그렸습니다. 밴드명의 머리글자인 ‘R’을 4분할해 만든 로고는 앨범 커버에서 프레임으로 활용할 수 있습니다.',
        koEtc: '작업범위: 로고, 앨범 커버 일러스트레이션</br>의뢰: 룸앤루머</br>제작시기: 2016년',
        imgs: ['01_mw1.jpg', '02_mw1.jpg',],
        video: { position: 'none', },
    },
    {
        number: 160801,
        thumb: 'jpg',
        type: ['Editorial'],
        en: 'Balzac’s Omelette',
        ko: '발자크의 식탁',
        enTxt: '〈Balzac’s Omelette〉 contains a rich analysis of the life and novels of the French novelist Balzac. The author tells the story by focusing on the food eaten by the Balzac and the French, passing through the stories and historical facts in Balzac’s novels and vividly portrays the contemporary French society. In the Korean translation, the names of unfamiliar French ingredients and dishes are written in detail as footnotes to help readers understand.',
        enEtc: 'Scope: Book design</br>Size: 175mm ✕ 200mm (268p)</br>Authour: Anka Muhlstein</br>Translator: Yeon Kim</br>Client: Yiyaginamu</br>Year: 2016',
        koTxt: '〈발자크의 식탁〉은 프랑스 소설가인 발자크의 생애와 소설에 대한 풍부한 분석을 담고 있습니다. 저자는 발자크와 프랑스 사람들이 먹던 음식에 초점을 맞추어 이야기를 풀어나가는데, 발자크의 소설 속 이야기와 역사적 사실을 넘나들며 당대 프랑스 사회의 모습을 생생하게 그려냅니다. 한국어 번역본에서는 독자들의 이해를 돕기 위해 생소한 프랑스 식재료와 요리 이름들을 각주로 자세히 풀어썼습니다. ',
        koEtc: '작업범위: 북디자인</br>판형: 175mm ✕ 200mm (268p)</br>저자: 앙카 멀스타인</br>번역: 김연</br>의뢰: 이야기나무</br>제작시기: 2016년',
        imgs: ['01_mw1.jpg', '02_mw1.jpg', '03_mw1.jpg', '04_mw1.jpg', '05_mw1.jpg'],
        video: { position: 'none', },
    },
    {
        number: 160603,
        thumb: 'jpg',
        type: ['Editorial', 'Graphics'],
        en: 'Idol Yearbook 2015',
        ko: '아이돌 연감 2015',
        enTxt: '‘Idology’ is a webzine specializing in idols, established in 2014. 〈Idol Yearbook 2015〉 is a book compiled by Idolology that summarizes various activities related to K-pop and idols during the year 2015. It introduces the album list and information released for a year, analyzes trends from various perspectives, and shows statistics on new idols who debuted in 2015 and examples of the debut process. All content is written in both Korean and English.',
        enEtc: 'Scope: Book design, infographic</br>Size: 127mm ✕ 188mm (192p)</br>Editor: Mimyo</br>Client: 3people</br>Year: 2018',
        koTxt: '‘아이돌로지’는 2014년 설립된 아이돌 전문 평론 웹진입니다. 〈아이돌 연감 2015〉는 아이돌로지가 2015년 한 해 동안의 케이팝과 아이돌에 관련된 다양한 활동을 결산해 엮은 책입니다. 1년간 발매된 음반 리스트와 정보를 소개하고 다양한 관점에서 경향을 분석하며, 2015년에 데뷔한 신인 아이돌 통계와 데뷔 과정 사례 등을 보여줍니다. 모든 내용은 한국어와 영어로 병기되었습니다. ',
        koEtc: '작업범위: 북디자인, 인포그래픽 제작</br>판형: 127mm ✕ 188mm (192p)</br>편집: 미묘</br>의뢰: 아이돌로지</br>제작시기: 2016년',
        imgs: ['01_mw1.jpg', '02_mw1.jpg', '03_mw1.jpg', '04_mw1.jpg', '05_mw1.jpg',],
        video: { position: 'none', },
    },
    {
        number: 160501,
        thumb: 'jpg',
        type: ['Branding', 'Graphics'],
        en: 'Microhabitat',
        ko: '미소서식지',
        enTxt: 'Identity and signage design of the co-working space ‘Microhabitat’. Microhabitat is a shared workspace for single-person cultural, ecological, and artistic activists. In order to express the appearance of the residents of the Microhabitat who create and manage their own lives in different shapes, a logo was created based on the appearance of microbes growing in each individual shape in the chalet.',
        enEtc: 'Scope: Logo, Signage</br>Client: Microhabitat</br>Year: 2016',
        koTxt: '코워킹스페이스 ‘미소서식지’의 아이덴티티와 사이니지 디자인입니다. 미소서식지는 1인 문화 ∙ 생태 ∙ 예술 활동가들을 위한 공유작업공간입니다. 서로 다른 모양으로 스스로의 삶을 창조하고 영위해나가는 미소서식지 입주자들의 모습을 표현하기 위해, 샬레 안에서 저마다의 모습을 키워가는 미생물의 모습을 본따 로고를 만들었습니다.',
        koEtc: '작업범위: 로고, 사이니지</br>의뢰: 미소서식지</br>제작시기: 2016년',
        imgs: ['01_tw1.jpg', '02_tw1.jpg', '03_tw1.jpg', '04_tw2.jpg', '05_tw2.jpg', '06_tw1.jpg', '07_tw1.jpg', '08_tw2.jpg', '09_tw2.jpg', '10_tw1.gif',],
        video: { position: 'none', },
    },

    // {
    //     number: 000000,
    //     thumb: 'jpg',
    //     type: [],
    //     en: '',
    //     ko: '',
    //     enTxt: '',
    //     enEtc: '',
    //     koTxt: '',
    //     koEtc: '',
    //     imgs: [],
    //     video: {position: 'none', },
    // },
];

